### ISSUE TITLE
Update T-Regx to 0.34

### ISSUE THREAD

**Issue by Danon** [veelkoov/fuzzrake#150]
Do you need help upgrading T-Regx to a newer versions? Do you event want/need to? :)

**Comment by veelkoov** [comment]
Thanks; I am currently focused on other things, but an update is definitely happening in the future.

**Comment by Danon** [comment]
No problemo!

we'll wait. Don't rush anything.

**Comment by Danon** [comment]
@veelkoov I recently release 0.38.0, would you be interested in me preparing a similar Pull Request?

**Comment by veelkoov** [comment]
I upgraded to 0.38 :+1: 
I opened the changelog somehow near the morning or null, and was gradually updating and testing, and I bumped to 0.38, reflected "was that version even released?" check on the changelog - nope it wasn't, checked in the terminal - it upgraded?, refreshed the changelog - oh, released 2 hours ago. :D
