### ISSUE TITLE
Service suspended on webpage

### ISSUE THREAD

**Issue by the-og-gear** [veelkoov/fuzzrake#204]
Apparently, service is suspended for multiple parts of the site - neither homepage nor feedback form appear to work.

![image](https://github.com/veelkoov/fuzzrake/assets/9438930/dcfabd18-c307-412f-8b5e-c4a825071e86)

It is unknown the length of time this has gone on, however.

**Comment by veelkoov** [comment]
Thank you for the report. Just right now the last remaining suspended part, submissions (I/U form), has been restored.
